### PR TITLE
Fixes to the source model for tests to pass

### PR DESCRIPTION
**Pull request by adivijaykumar**

### CODE REVIEW

**Comment by adivijaykumar** [comment]
https://git.ligo.org/aditya.vijaykumar/bilby_github/-/pipelines/192851 -- tests pass. @Kruthi24 could you test this branch with the likelihood notebooks like we had discussed?

Please also feel free to review the changes in this branch.

**Comment by krishnakruthi** [comment]
> @Kruthi24 could you test this branch with the likelihood notebooks like we had discussed?

I checked if the likelihoods matched for fiducial parameters and if the strain calculated with `get_detector_response_relative_binning` and `get_detector_response` matched at the bin edges. Anything else?

**Comment by krishnakruthi** [comment]
I also ran the sampler.

**Comment by adivijaykumar** [comment]
Thanks! Could you also calculate the likelihood for parameters different from the fiducial waveform and see if they match?

**Comment by krishnakruthi** [comment]
> Could you also calculate the likelihood for parameters different from the fiducial waveform and see if they match?

I checked this for a couple of values. They were in the same ballpark always

**Comment by adivijaykumar** [comment]
Thanks! Shall I merge then?

**Comment by krishnakruthi** [comment]
Yup!

**Pull request merged**
