### PR TITLE
Add frequency masks in get_detector_response_relative_binning

### PR DESCRIPTION
**Pull request by krishnakruthi**

### CODE REVIEW

**Comment by adivijaykumar** [comment]
First question: Did you do a consistency check with `init_params`?

Also, the new changes in `relbin` have not been pulled to `relbin_kruthi`, so please pull them before you run a test.

**Comment by krishnakruthi** [comment]
Yup. I basically cross-checked the output of `get_detector_response_relative_binning`with the output of `get_detector_response`. I also ran the `bilby_likelihood_error.py` script for different epsilon values.

Have there been any new changes to `relbin` since last night?

**Comment by adivijaykumar** [comment]
No, but the commit history is different for the branches. Hence asked.

**Comment by krishnakruthi** [comment]
Fixed it.

**Comment by adivijaykumar** [comment]
Did you run the tests also?

**Comment by krishnakruthi** [comment]
> Yup. I basically cross-checked the output of `get_detector_response_relative_binning`with the output of `get_detector_response`. I also ran the `bilby_likelihood_error.py` script for different epsilon values.

Just these.

**Comment by adivijaykumar** [comment]
Merging this PR, by noting #18.

**Pull request merged**
